---
variables:
  WERF_VERSION: "1.2 ea"

.base_werf: &base_werf
  - set -x
  - type multiwerf && . $(multiwerf use ${WERF_VERSION} --as-file)
  - type werf && source $(werf ci-env gitlab --as-file --verbose)

.base_deploy: &base_deploy
  stage: deploy
  script:
    - *base_werf
    - werf converge --skip-build --set "env_url=$(echo ${CI_ENVIRONMENT_URL} | cut -d / -f 3)"
      --namespace ${CI_ENVIRONMENT_SLUG}
  dependencies:
    - Build
  tags:
    - werf

stages:
  - build
  - deploy
  - cleanup

Build:
  stage: build
  script:
    - *base_werf
    - werf build
  except:
    - schedules
  tags:
    - werf

Deploy to Test:
  <<: *base_deploy
  stage: deploy
  environment:
    name: test
    url: https://test-kube.timebook.ru
  when: manual
  except:
    - schedules
  tags:
    - werf

Cleanup:
  stage: cleanup
  script:
    - *base_werf
    - docker login -u nobody -p ${WERF_IMAGES_CLEANUP_PASSWORD} ${WERF_REPO}
    - werf cleanup
  only:
    - schedules
  tags:
    - werf
