debug: false
bro:
  flow:
    stage:
      name: default.domain.com
      uri: https://${bro.flow.stage.name}
      branchName: stages/${bro.flow.stage.name}
      pushCmd: git checkout -b ${bro.flow.stage.branchName} && git push -u origin ${bro.flow.stage.branchName} --force
      mergeCmd: git merge -m "Merge branch '{branchName}' into stage '${bro.flow.stage.branchName}'" origin/{branchName} --no-ff
      cronReceive: "0 */10 * * * ?"
      basePath: /bro
      deploy:
        jobName: Deploy to Stage (example)
      git:
        cronReceive: "0 */1 * * * ?"
        userName: Bender Rodriguez
        userEmail: bender@company.com
      temp:
        initDir: init
        tempDir: temp/projects
        cleanAfter: P-14D
    task-trackers:
      redmine:
        host: https://redmine.domain.com
        apiKey: ACCESS_TOKEN
        afterUpdateTime: P-30D # period for the tasks where changes may be applied
        timeout: 30000
        trackers:
          - id: 001
        statuses:
          - id: 002
            needMerge: false
          - id: 003
            needMerge: true
          - id: 004
            needMerge: true
        custom-fields:
          - id: 005
          - id: 006
          - id: 007
        enabled: true
      jira:
        host: https://company.atlassian.net
        username: USERNAME
        apiToken: API_TOKEN
        issues:
          mergeJQL: "'Stage[Select List (multiple choices)]'=${bro.flow.stage.name} AND statusCategory IN ('In Progress')"
          label-deployment-failed: DeploymentFailed
          label-deployment-successful: DeploymentSuccessful
        enabled: true
    repositories:
      gitlab:
        host: https://gitlab.domain.com
        token: ACCESS_TOKEN
        proxy:
        enabled: true
        timeout: 60000
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr([%15.15t]){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %msg%n"
  level:
    ru.timebook.bro.*: trace
spring:
  main:
    banner-mode: off
    lazy-initialization: true
  datasource:
    url: jdbc:h2:file:./temp/database/store
    driver-class-name: org.h2.Driver
    username: bender
    password: bender
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
  mustache:
    suffix: .html
    prefix: classpath:/static/
  groovy:
    template:
      check-template-location: false
  aop:
    auto: false
    proxy-target-class: false
server:
  tomcat:
    threads:
      max: 5
      min-spare: 1
    connection-timeout: 30
  servlet:
    context-path: ${bro.flow.stage.basePath}