debug: false

bro:
  flow:
    stage:
      name: test-kube.timebook.ru
      cronReceive: "0 */1 * * * ?"
      git:
        userEmail: bender@corp.timebook.ru
    task-trackers:
      redmine:
        host: https://redmine.timebook.ru
        apiKey: {{ pluck .Values.werf.env .Values.token.redmine | first | default .Values.token.redmine._default }}
        enabled: true
        trackers:
          - id: 13 # Исправление/доработка
        statuses:
          - id: 4 # Ожидает
            needMerge: false
          - id: 7 # Создан pull request
            needMerge: true
          - id: 9 # Требуется проверка
            needMerge: true
        custom-fields:
          - id: 1 # Pull Request back-end
          - id: 4 # Pull Request front-end
          - id: 19 # Pull Request erpi
      jira:
        host: https://timebook-jira.atlassian.net
        username: it@timebook.ru
        apiToken: {{ pluck .Values.werf.env .Values.token.jira | first | default .Values.token.jira._default }}
        enabled: true
    repositories:
      gitlab:
        host: https://gitlab.timebook.cloud
        token: {{ pluck .Values.werf.env .Values.token.gitlab | first | default .Values.token.gitlab._default }}
        repositories:
          - path: DEVOPS/bender
            preMerge: master
          - path: timebook/timebook
            preMerge: master
          - path: timebook/timebook.web-client
            preMerge: master
          - path: IT/DEV/shift-sender
            preMerge: master
          - path: IT/DEV/Node-MS/auchan-ms
            preMerge: master
          - path: IT/DEV/Node-MS/lenta-ms
            preMerge: master
          - path: IT/DEV/Node-MS/document-ms
            preMerge: master
          - path: IT/DEV/web-sockets
            preMerge: master
          - path: IT/DEV/recognition/surf
            preMerge: master

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(${LOG_LEVEL_PATTERN:%5p}) %msg%n"
  level:
    ru.timebook.bro.*: trace

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:file:./temp/database/store
    driver-class-name: org.h2.Driver
    username: bender
    password: bender
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        cachecontrol:
          no-cache: true
  mustache:
    suffix: .html
    prefix: classpath:/static/
  groovy:
    template:
      check-template-location: false

server:
  tomcat:
    threads:
      max: 5
      min-spare: 1
    connection-timeout: 30
  servlet:
    context-path: ${bro.flow.stage.basePath}
