apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
data:
  application.yml: |
    bro:
      flow:
        stage:
          name: test-kube.timebook.ru
          cronReceive: “0 */1 * * * ?”
          git:
            userEmail: bender@corp.timebook.ru
        task-trackers:
          redmine:
            host: https://redmine.timebook.ru
            apiKey: {{ pluck .Values.global.env .Values.token.redmine | first | default .Values.token.redmine._default }}
            enabled: true
            trackers:
              - id: 13 # Исправление/доработка
            statuses:
              - id: 4 # Ожидает
                needMerge: false
              - id: 7 # Создан pull request
                needMerge: true
              - id: 9 # Требуется проверка
                needMerge: true
            custom-fields:
              - id: 1 # Pull Request back-end
              - id: 4 # Pull Request front-end
              - id: 19 # Pull Request erpi
          jira:
            host: https://timebook-jira.atlassian.net
            username: it@timebook.ru
            apiToken: {{ pluck .Values.global.env .Values.token.jira | first | default .Values.token.jira._default }}
            enabled: true
        repositories:
          gitlab:
            host: https://gitlab.timebook.cloud
            token: {{ pluck .Values.global.env .Values.token.gitlab | first | default .Values.token.gitlab._default }}
            repositories:
              - path: DEVOPS/bender
                preMerge: master
              - path: timebook/timebook
                preMerge: master
              - path: timebook/timebook.web-client
                preMerge: master
              - path: IT/DEV/shift-sender
                preMerge: master
              - path: IT/DEV/Node-MS/auchan-ms
                preMerge: master
              - path: IT/DEV/Node-MS/lenta-ms
                preMerge: master
              - path: IT/DEV/Node-MS/document-ms
                preMerge: master
              - path: IT/DEV/web-sockets
                preMerge: master
              - path: IT/DEV/recognition/surf
                preMerge: master
  git_key.private: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACA8LF0emjQBIJI5xtyQwc848GVmL9sDX4qu7OW90FPlKwAAAJjbDSNx2w0j
    cQAAAAtzc2gtZWQyNTUxOQAAACA8LF0emjQBIJI5xtyQwc848GVmL9sDX4qu7OW90FPlKw
    AAAECvdnetSPfdEvkOIHZwzEVvX/Bl5tpYejyZ4oMj/fbPYTwsXR6aNAEgkjnG3JDBzzjw
    ZWYv2wNfiq7s5b3QU+UrAAAAD2Jyb0B0aW1lYm9vay5ydQECAwQFBg==
    -----END OPENSSH PRIVATE KEY-----

