---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  replicas: {{ pluck .Values.werf.env .Values.app.replicas | first | default .Values.app.replicas._default }}
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ .Chart.Name | quote }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/01-configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
      - name: registrysecret
      volumes:
        - name: configs
          configMap:
            name: "{{ .Chart.Name }}-config"
        - name: id-rsa
          secret:
            defaultMode: 0600
            secretName: id-rsa
      containers:
      - name: {{ .Chart.Name | quote }}
{{ tuple "bro" . | include ".Values.werf.image.IMAGE_NAME" | indent 8 }}
        workingDir: /app
        securityContext:
          runAsUser: 7000
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: configs
          mountPath: /app/application.yml
          subPath: application.yml
        - name: id-rsa
          mountPath: /app/id_rsa
          subPath: id_rsa
          readOnly: false
resources:
          requests:
            cpu: {{ pluck .Values.werf.env .Values.app.resources.requests.cpu | first | default .Values.app.resources.requests.cpu._default }}
            memory: {{ pluck .Values.werf.env .Values.app.resources.requests.memory | first | default .Values.app.resources.requests.memory._default }}
          limits:
            memory: {{ pluck .Values.werf.env .Values.app.resources.limits.memory | first | default .Values.app.resources.limits.memory._default }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
          initialDelaySeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
          initialDelaySeconds: 10
        env:
{{- include "common_envs" . | indent 8 }}
        command:
        - "java $JAVA_OPTS -jar bro.jar"
---
apiVersion: v1
data:
  id_rsa: {{ tuple "id_rsa" . | include "werf_secret_file" | b64enc }}
kind: Secret
metadata:
  name: id-rsa
type: Opaque
